language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config flex bison xsltproc docbook-xsl libevtlog-dev libnet1-dev libglib2.0-dev libdbi0-dev libssl-dev libjson0-dev libwrap0-dev libpcre3-dev libcap-dev libesmtp-dev libgeoip-dev libhiredis-dev sqlite3 libdbd-sqlite3
before_script:
  - ./autogen.sh
script:
  - ./configure --with-ivykis=internal --prefix=$HOME/install/syslog-ng --enable-pacct
  - make
  - make check VERBOSE=1
  - make func-test VERBOSE=1
compiler:
  - gcc
  - clang
branches:
  except:
    - /wip/
notifications:
  irc:
    channels:
      - "irc.freenode.org#balabit"
